networks:
  loki: {}

volumes:
  minio-data: {}
  grafana-data: {}

services:
  loki:
    image: grafana/loki:3.4.3
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml:ro
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki

  alloy:
    image: grafana/alloy:v1.7.5
    restart: unless-stopped
    volumes:
      - ./config/alloy/syslog-config.alloy:/etc/alloy/config.alloy:ro
    depends_on:
      loki:
        condition: service_healthy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "514:514/udp"
    networks:
      - loki

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    restart: unless-stopped
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      MINIO_ROOT_USER: loki
      MINIO_ROOT_PASSWORD: changeme
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_UPDATE: off
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - loki

  grafana:
    image: grafana/grafana:11.6.0
    restart: unless-stopped
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loki
