server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  replication_factor: 1
  path_prefix: ${LOKI_PATH_PREFIX}
  storage:
    s3:
      bucketnames: ${LOKI_S3_DATA_BUCKET_NAME}
      endpoint: minio:9000
      insecure: true
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      s3forcepathstyle: true
  ring:
    kvstore:
      store: inmemory

ruler:
  storage:
    s3:
      bucketnames: ${LOKI_S3_RULER_BUCKET_NAME}

compactor:
  working_directory: ${LOKI_COMPACTOR_WORKING_DIR}
  retention_enabled: ${LOKI_COMPACTOR_RETENTION_ENABLED}
  delete_request_store: s3

limits_config:
  retention_period: ${LOKI_COMPACTOR_RETENTION_PERIOD}
