auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  replication_factor: 1
  path_prefix: /loki
  storage:
    s3:
      bucketnames: loki-data
      endpoint: minio:9000
      insecure: true
      access_key_id: loki
      secret_access_key: changeme
      s3forcepathstyle: true
  ring:
    kvstore:
      store: inmemory

ruler:
  storage:
    s3:
      bucketnames: loki-ruler

compactor:
  working_directory: /tmp/compactor
  retention_enabled: true
  delete_request_store: s3

limits_config:
  retention_period: 336h

analytics:
  reporting_enabled: false
